name: Run Automation Tests

on:
  push:
    branches:
      - main  # Runs when changes happen in the automation repo
  repository_dispatch:
    types: [run-tests]  # Triggered from project repo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Clean Old Screenshots
        run: rm -rf screenshots/* || true

      - name: Run Automation Tests
        run: mvn test  # Change to your test execution command

      - name: copy HTML Report
        run: |
          mkdir -p test-results/test-output
          cp -r test-output/* test-results/test-output/

      - name: Copy Screenshots to Test Results
        run: |
          mkdir -p test-results/test-output/screenshots
          cp -r screenshots/* test-results/test-output/screenshots/

      - name: Zip Screenshots
        run: |
          zip -r test-results/screenshots.zip screenshots/
          
      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: test-results

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Test Execution Report - ${{ github.repository }}"
          to: "keerthana.elango@indegene.com"
          from: "GitHub Actions <githubActions@example.com>"
          content_type: text/html
          attachments: |
            test-results/test-output/ExtentReport.html
            test-results/screenshots.zip
          body: |
            Test Results
            Find the attached test execution report.
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}

