name: Run Automation Tests

on:
  push:
    branches:
      - main  # Runs when changes happen in the automation repo
  repository_dispatch:
    types: [run-tests]  # Triggered from project repo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run Automation Tests
        run: mvn test  # Change to your test execution command
